In [5]:
import yfinance as yf
import pandas as pd

In [6]:
# define tickers and load data from the last 2 years
tickers = ["AAPL", "MSFT", "JPM"]
data = yf.download(tickers, period="2y")["Close"]

data.head()

[*********************100%***********************]  3 of 3 completed

Ticker            AAPL         JPM        MSFT
Date
2024-05-15  188.090683  193.760651  417.435974
2024-05-16  188.209625  194.105774  415.373871
2024-05-17  188.239365  196.329956  414.604309
2024-05-20  189.399323  187.500412  419.665863
2024-05-21  190.698105  191.277634  423.316528

In [8]:
#temporarily saveing the data in a csv to access it from other notebooks
data.to_csv("../data/stock_data.csv")

print("Saved successfully!")

Saved successfully!

In [12]:
#load metadata for defined tickers
meta = {}
for ticker in ["AAPL", "MSFT", "JPM"]:
    info = yf.Ticker(ticker).info
    meta[ticker] = {
        "sector": info.get("sector", "N/A"),
        "country": info.get("country", "N/A"),
        "industry": info.get("industry", "N/A")
    }
data.head()

Ticker            AAPL         JPM        MSFT
Date
2024-05-15  188.090683  193.760651  417.435974
2024-05-16  188.209625  194.105774  415.373871
2024-05-17  188.239365  196.329956  414.604309
2024-05-20  189.399323  187.500412  419.665863
2024-05-21  190.698105  191.277634  423.316528

In [14]:
#saving metadata in separate CSV
meta_df = pd.DataFrame(meta).T
meta_df.to_csv("../data/metadata.csv")
print("Saved successfully!")

Saved successfully!

In [18]:
#load benchmark data and saving in CSV to calculate alpha in Notebook 02
benchmark = yf.download("^GSPC", period = "2y")["Close"]
benchmark.to_csv("../data/benchmark.csv")

print("Saved successfully")

[*********************100%***********************]  1 of 1 completed

Saved successfully